<?php
/**
 * Activator Class
 *
 * @package PSP_Territorial
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class PSP_Territorial_Activator
 *
 * Runs on plugin activation.
 */
class PSP_Territorial_Activator {

	/**
	 * Activate the plugin.
	 */
	public static function activate() {
		require_once PSP_TERRITORIAL_PLUGIN_DIR . 'includes/class-psp-database.php';

		$db = new PSP_Territorial_Database();
		$db->create_tables();

		// Import data if table is empty.
		if ( self::should_import() ) {
			require_once PSP_TERRITORIAL_PLUGIN_DIR . 'includes/class-psp-utils.php';
			require_once PSP_TERRITORIAL_PLUGIN_DIR . 'includes/class-psp-importer.php';
			require_once PSP_TERRITORIAL_PLUGIN_DIR . 'includes/class-psp-importer-v2.php';

			// Prefer the clean JSON generated by scripts/clean_csv_to_json.py,
			// then fall back to the bundled panama_data.json.
			$clean_path  = PSP_TERRITORIAL_PLUGIN_DIR . 'assets/data/panama_clean.json';
			$legacy_path = PSP_TERRITORIAL_PLUGIN_DIR . 'assets/data/panama_data.json';
			$json_path   = file_exists( $clean_path ) ? $clean_path : $legacy_path;

			$importer = new PSP_Importer_V2( $db );
			$importer->import_from_file( $json_path );
		}

		// Set a flag to flush rewrite rules.
		update_option( 'psp_territorial_flush_rewrite', 1 );
	}

	/**
	 * Determine whether to auto-import data.
	 *
	 * @return bool
	 */
	private static function should_import() {
		global $wpdb;
		$db    = new PSP_Territorial_Database();
		$table = $db->get_table_name();
		// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$count = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$table}" );
		return $count === 0;
	}
}
